-- TLC-mission CRM — Seed Data
-- สำหรับเริ่มต้นระบบด้วย 6 Body หลัก

-- ── 1. BODIES (TENANTS) ──
-- Note: UUIDs are hardcoded here for consistent development setup
-- In production, these would be generated by Supabase

INSERT INTO bodies (id, name, code, color_hex, sort_order)
VALUES 
  ('3b82f600-0000-0000-0000-000000000001', 'เมือง 1', 'body_1', '#3b82f6', 1),
  ('06b6d400-0000-0000-0000-000000000002', 'เมือง 2', 'body_2', '#06b6d4', 2),
  ('8b5cf600-0000-0000-0000-000000000003', 'สมเด็จ', 'body_3', '#8b5cf6', 3),
  ('10b98100-0000-0000-0000-000000000004', 'ท่าคันโท', 'body_4', '#10b981', 4),
  ('f59e0b00-0000-0000-0000-000000000005', 'กุฉินารายณ์', 'body_5', '#f59e0b', 5),
  ('ec489900-0000-0000-0000-000000000006', 'คำใหญ่', 'body_6', '#ec4899', 6);

-- ── 2. CARE GROUPS (Example for Body 1) ──
INSERT INTO care_groups (body_id, code, leader_name, village, sort_order)
VALUES
  ('3b82f600-0000-0000-0000-000000000001', 'G01', 'ผุสดี', 'หมู่บ้านสุขสันต์', 1),
  ('3b82f600-0000-0000-0000-000000000001', 'G02', 'เบญ', 'หมู่บ้านพัฒนา', 2),
  ('3b82f600-0000-0000-0000-000000000001', 'G03', 'ปุนนาภา', 'หมู่บ้านร่มเย็น', 3),
  ('3b82f600-0000-0000-0000-000000000001', 'G04', 'ทัศนา', 'หมู่บ้านสามัคคี', 4);

-- ── 3. MEMBERS (Example for G01) ──
-- First, get the id of G01 (in a real script we'd use subqueries or variables)
-- For this seed, we'll just insert a few members.

INSERT INTO members (body_id, full_name, nickname, age, is_active)
VALUES
  ('3b82f600-0000-0000-0000-000000000001', 'สมชาย ใจดี', 'ชาย', 45, true),
  ('3b82f600-0000-0000-0000-000000000001', 'สมหญิง รักดี', 'หญิง', 42, true),
  ('3b82f600-0000-0000-0000-000000000001', 'วิชัย กล้าหาญ', 'ชัย', 30, true);

-- ── 4. PILLAR TARGETS (Optional meta-data table or hardcoded in logic) ──
-- In this blueprint, targets are often discussed as fixed but can be dynamic.
-- We'll assume for now they are managed in the UI or a separate config table.
